# Generated by Django 4.2.7 on 2025-06-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_receipt_authorization_code_receipt_card_last_four_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='authorization_code',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='card_last_four',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='cashier_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='category',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='merchant_address',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='merchant_email',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='merchant_phone',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='store_number',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='tip_amount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='transaction_type',
        ),
        migrations.DeleteModel(
            name='ReceiptItem',
        ),
    ]
